### ISSUE TITLE
#9 basic layout 9

### ISSUE THREAD

**Issue by Sebastiaan-hva** [Sebastiaan-hva/layout-in-css#3]

**Comment by sebas-hagoort** [comment]
![image](https://github.com/user-attachments/assets/d82c88a1-9ff1-4d02-b280-6ed5d4a9985a)

**Comment by sebas-hagoort** [comment]
![image](https://github.com/user-attachments/assets/50efab4d-d4b0-4e52-9b88-7a60a7f98798)
#fixes werkte niet
